# templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Release.Name }}
