version: 0.2

env:
  variables:
    ECR_REPO: "674622770595.dkr.ecr.us-east-1.amazonaws.com/sre-challenge-app"
    IMAGE_TAG: "$CODEBUILD_RESOLVED_SOURCE_VERSION"

phases:
  install:
    commands:
      - echo "Instalando dependências do Maven..."
      - cd app
      - mvn clean install --batch-mode --update-snapshots

  pre_build:
    commands:
      - echo "Fazendo login no Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO
      - REPO_URI=$(aws ecr describe-repositories --repository-names sre-challenge-app --query "repositories[0].repositoryUri" --output text)

  build:
    commands:
      - echo "Mudando para o diretório de código..."
      - cd app
      - echo "Executando os testes..."
      - mvn test
      - echo "Compilando o projeto..."
      - mvn clean package -DskipTests
      - echo "Buildando a imagem Docker..."
      - docker build -t $REPO_URI:$IMAGE_TAG .
      - docker tag $REPO_URI:$IMAGE_TAG $REPO_URI:latest

  post_build:
    commands:
      - echo "Enviando a imagem para o ECR..."
      - docker push $REPO_URI:$IMAGE_TAG
      - docker push $REPO_URI:latest
      - echo "Gerando arquivo de metadados da imagem..."
      - echo "ECR_IMAGE=$REPO_URI:$IMAGE_TAG" > imageDetail.txt

artifacts:
  files:
    - imageDetail.txt
  discard-paths: yes
