Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: sre-challenge-springboot-pipeline
      RoleArn: arn:aws:iam::674622770595:role/codepipeline-role
      ArtifactStore:
        Type: S3
        Location: your-codepipeline-bucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                RepositoryName: "sre-challenge-app"
                BranchName: "main"
              RunOrder: 1

        - Name: Build
          Actions:
            - Name: BuildMaven
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: "sre-challenge-build"
              RunOrder: 1

        - Name: Test
          Actions:
            - Name: RunTests
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              OutputArtifacts:
                - Name: TestOutput
              Configuration:
                ProjectName: "sre-challenge-test"
              RunOrder: 1

        - Name: DockerBuild
          Actions:
            - Name: BuildDockerImage
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: "sre-challenge-docker"
              RunOrder: 1

        - Name: Deploy
          Actions:
            - Name: DeployHelm
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: "sre-challenge-deploy"
              RunOrder: 1
