# values.yaml

replicaCount: 2

image:
  repository: 674622770595.dkr.ecr.us-east-1.amazonaws.com/sre-challenge
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internal"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/subnets: subnet-043be10d9c45a7b00, subnet-0e8b00c66b770a0f0
    alb.ingress.kubernetes.io/security-groups: sg-0d767ea4ef8151def
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
  hosts:
    - host: sre.challenge.itau
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sre-challenge-app-service
              port:
                number: 8080
  pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env: []

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1